# Generated by Django 3.0 on 2019-12-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myuser',
            unique_together={('use_max', 'phonenum')},
        ),
        migrations.AlterIndexTogether(
            name='myuser',
            index_together={('use_max', 'phonenum')},
        ),
    ]
