# Generated by Django 2.2.5 on 2019-12-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='Agency_name',
        ),
    ]
