# Generated by Django 2.2.5 on 2019-12-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Plan_ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='Plan_name',
            field=models.CharField(max_length=50),
        ),
    ]
